apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
        - name: ai
          image: 428185450315.dkr.ecr.ap-northeast-2.amazonaws.com/dgu-cap-ai:latest
          imagePullPolicy: Never   # kind load로 로드한 이미지 사용
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ai
spec:
  selector:
    app: ai
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
